"""initial filing_documents and transactions

Revision ID: 0a8e2fcc1402
Revises: 
Create Date: 2026-06-21 08:46:41.732656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0a8e2fcc1402'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_document_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('index_url', sa.Text(), nullable=True),
    sa.Column('filing_type', sa.String(length=100), nullable=True),
    sa.Column('filing_year', sa.Integer(), nullable=True),
    sa.Column('filer_name', sa.String(length=255), nullable=False),
    sa.Column('filer_bioguide_id', sa.String(length=20), nullable=True),
    sa.Column('filer_state', sa.String(length=2), nullable=True),
    sa.Column('filer_district', sa.String(length=10), nullable=True),
    sa.Column('chamber', sa.String(length=20), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('pdf_size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('raw_index_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parser_status', sa.Enum('pending', 'parsed', 'partial', 'failed', 'needs_review', name='parserstatus', native_enum=False, length=20), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('parser_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_error', sa.Text(), nullable=True),
    sa.Column('parser_confidence', sa.Float(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_document_id', name='uq_filing_documents_source_doc')
    )
    op.create_index(op.f('ix_filing_documents_pdf_sha256'), 'filing_documents', ['pdf_sha256'], unique=False)
    op.create_index(op.f('ix_filing_documents_source'), 'filing_documents', ['source'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_document_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('asset_name_raw', sa.Text(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('security_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('amount_range_raw', sa.String(length=100), nullable=True),
    sa.Column('amount_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('capital_gains_over_200', sa.Boolean(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('raw_extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('parser_confidence', sa.Float(), nullable=True),
    sa.Column('parser_notes', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_document_id'], ['filing_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_document_id', 'source_transaction_id', name='uq_transactions_filing_doc_source_txn')
    )
    op.create_index(op.f('ix_transactions_filing_document_id'), 'transactions', ['filing_document_id'], unique=False)
    op.create_index(op.f('ix_transactions_needs_review'), 'transactions', ['needs_review'], unique=False)
    op.create_index(op.f('ix_transactions_ticker'), 'transactions', ['ticker'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ticker'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_needs_review'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_filing_document_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_filing_documents_source'), table_name='filing_documents')
    op.drop_index(op.f('ix_filing_documents_pdf_sha256'), table_name='filing_documents')
    op.drop_table('filing_documents')
    # ### end Alembic commands ###
