"""add enrichment_items and alert_enrichments

Revision ID: 54043df816b7
Revises: b48ff69c2322
Create Date: 2026-06-21 13:02:05.827011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '54043df816b7'
down_revision: Union[str, None] = 'b48ff69c2322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('form_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_enrichment_items_source_external_id')
    )
    op.create_index(op.f('ix_enrichment_items_source'), 'enrichment_items', ['source'], unique=False)
    op.create_index(op.f('ix_enrichment_items_ticker'), 'enrichment_items', ['ticker'], unique=False)
    op.create_table('alert_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('enrichment_item_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrichment_item_id'], ['enrichment_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'enrichment_item_id', name='uq_alert_enrichments_alert_item')
    )
    op.create_index(op.f('ix_alert_enrichments_alert_id'), 'alert_enrichments', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_enrichments_enrichment_item_id'), 'alert_enrichments', ['enrichment_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_enrichments_enrichment_item_id'), table_name='alert_enrichments')
    op.drop_index(op.f('ix_alert_enrichments_alert_id'), table_name='alert_enrichments')
    op.drop_table('alert_enrichments')
    op.drop_index(op.f('ix_enrichment_items_ticker'), table_name='enrichment_items')
    op.drop_index(op.f('ix_enrichment_items_source'), table_name='enrichment_items')
    op.drop_table('enrichment_items')
    # ### end Alembic commands ###
