"""add daily_digests and daily_digest_deliveries

Revision ID: b48ff69c2322
Revises: bcd56269c137
Create Date: 2026-06-21 12:09:40.691018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b48ff69c2322'
down_revision: Union[str, None] = 'bcd56269c137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.Enum('profile', 'cross_profile', name='digestscope', native_enum=False, length=20), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('generated', 'sent', 'partial', 'failed', name='digeststatus', native_enum=False, length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_date', 'timezone', 'scope', 'profile_id', name='uq_daily_digests_date_tz_scope_profile')
    )
    op.create_index(op.f('ix_daily_digests_digest_date'), 'daily_digests', ['digest_date'], unique=False)
    op.create_index(op.f('ix_daily_digests_profile_id'), 'daily_digests', ['profile_id'], unique=False)
    op.create_table('daily_digest_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_digest_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'slack', name='deliverychannel', native_enum=False, length=20), nullable=False),
    sa.Column('destination_label', sa.String(length=255), nullable=True),
    sa.Column('destination_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'skipped', name='deliverystatus', native_enum=False, length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_digest_id'], ['daily_digests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_digest_id', 'channel', 'destination_hash', name='uq_daily_digest_deliveries_digest_channel_dest')
    )
    op.create_index(op.f('ix_daily_digest_deliveries_daily_digest_id'), 'daily_digest_deliveries', ['daily_digest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_digest_deliveries_daily_digest_id'), table_name='daily_digest_deliveries')
    op.drop_table('daily_digest_deliveries')
    op.drop_index(op.f('ix_daily_digests_profile_id'), table_name='daily_digests')
    op.drop_index(op.f('ix_daily_digests_digest_date'), table_name='daily_digests')
    op.drop_table('daily_digests')
    # ### end Alembic commands ###
