"""add profiles, profile_rules, alerts

Revision ID: ce2730fff72d
Revises: 0a8e2fcc1402
Create Date: 2026-06-21 11:48:02.740548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ce2730fff72d'
down_revision: Union[str, None] = '0a8e2fcc1402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('filer_bioguide_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filer_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chambers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tickers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sectors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transaction_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_filing_delay_days', sa.Integer(), nullable=True),
    sa.Column('min_parser_confidence', sa.Float(), nullable=False),
    sa.Column('include_needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_rules_profile_id'), 'profile_rules', ['profile_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profile_rule_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('filing_document_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'read', 'dismissed', name='alertstatus', native_enum=False, length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filer_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('ticker_snapshot', sa.String(length=20), nullable=True),
    sa.Column('asset_name_snapshot', sa.Text(), nullable=True),
    sa.Column('transaction_type_snapshot', sa.String(length=20), nullable=True),
    sa.Column('amount_min_snapshot', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_max_snapshot', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('transaction_date_snapshot', sa.Date(), nullable=True),
    sa.Column('filed_at_snapshot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filing_delay_days_snapshot', sa.Integer(), nullable=True),
    sa.Column('parser_confidence_snapshot', sa.Float(), nullable=True),
    sa.Column('needs_review_snapshot', sa.Boolean(), nullable=True),
    sa.Column('source_url_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_document_id'], ['filing_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_rule_id'], ['profile_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'profile_rule_id', 'transaction_id', name='uq_alerts_profile_rule_transaction')
    )
    op.create_index(op.f('ix_alerts_filing_document_id'), 'alerts', ['filing_document_id'], unique=False)
    op.create_index(op.f('ix_alerts_profile_id'), 'alerts', ['profile_id'], unique=False)
    op.create_index(op.f('ix_alerts_profile_rule_id'), 'alerts', ['profile_rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_transaction_id'), 'alerts', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_transaction_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_profile_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_profile_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_filing_document_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_profile_rules_profile_id'), table_name='profile_rules')
    op.drop_table('profile_rules')
    op.drop_table('profiles')
    # ### end Alembic commands ###
